on:
  workflow-call:
  inputs:
    node-version:
      description: 'Node.js version'
      required: false
      default: 18

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  # We only install Chromium manually
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

jobs:
  - uses: actions/checkout@v3
  - uses: pnpm/action-setup@v2.2.4
  - uses: actions/setup-node@v3
    with:
      node-version: ${{ github.event.inputs.node-version }}
      cache: pnpm
  - run: pnpm install --frozen-lockfile
  - run: pnpm playwright install chromium
